contentColumnType: json
fieldGroup: 14c4714f-0eaa-45a8-b373-20c65d99f6e1 # Common
handle: testField
instructions: ''
name: 'test field'
searchable: false
translationKeyFormat: null
translationMethod: none
type: Developion\Core\fields\TestField
