enableVersioning: true
handle: dev
name: Dev
propagationMethod: all
siteSettings:
  33bc1f7c-cf69-4e2d-aa65-dfcc22722248: # Craft Dev
    enabledByDefault: true
    hasUrls: true
    template: entry
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 7b78f58c-0592-402c-af61-5aaf8eecde82
type: structure
