enableVersioning: true
handle: testSection
name: 'Test Section'
propagationMethod: all
siteSettings:
  33bc1f7c-cf69-4e2d-aa65-dfcc22722248: # Craft Dev
    enabledByDefault: true
    hasUrls: true
    template: test-section/_entry
    uriFormat: 'test-section/{slug}'
structure:
  maxLevels: null
  uid: 5e241357-e7c5-4a33-ab81-92c7ce2cce3a
type: structure
